import { useState } from "react";
import { action, submitFeedback } from "../api";
const categories = ["Estate", "Transport", "Environment", "Other"];
export function CitizenPage({ session }) {
  const [message, setMessage] = useState(""), [category, setCategory] = useState(""), [result, setResult] = useState(null), [error, setError] = useState(""), [audio, setAudio] = useState(null);
  async function submit(event) { event.preventDefault(); const value = message.trim(); if (!value) return setError("Please enter feedback that is not blank."); if (value.length > 500) return setError("Feedback must be 500 characters or fewer."); setError(""); try { setResult(await submitFeedback(session, { message: value, category })); setMessage(""); } catch (e) { setError(e.message); } }
  async function speak() { try { const result = await action(session, result.feedback.id, "audio"); setAudio(`data:${result.mimeType || "audio/mpeg"};base64,${result.audioBase64}`); } catch (e) { setError(e.message); } }
  return <main className="page-shell"><div className="page-heading"><div className="eyebrow">Public feedback</div><h1>What would you like us to know?</h1></div><section className="form-card">{result ? <div className="success-banner" role="status"><h2>Thank you — your feedback was received.</h2><p>Your reference is <strong>{result.reference}</strong>.</p>{audio ? <audio controls src={audio} /> : <button className="text-button" onClick={speak}>Read feedback aloud</button>}<button className="primary-button" onClick={() => { setResult(null); setError(""); setAudio(null); }}>Submit another</button></div> : <form onSubmit={submit}><label htmlFor="category">Category<select id="category" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Auto-detect category</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label htmlFor="feedback">Your feedback<textarea id="feedback" rows="7" value={message} maxLength="500" aria-describedby="count" aria-invalid={!!error} onChange={(e) => setMessage(e.target.value)} placeholder="Share your feedback here..." /></label><div className="form-footer"><span id="count" className="muted">{message.length}/500 characters</span><button className="primary-button">Submit feedback</button></div></form>}{error && <p className="error-message" role="alert">{error}</p>}</section></main>;
}
